MAX_EXPORTED_MESSAGES: 1000000
ALL_COLUMNS:
  - timestamp
  - conversationId
  - conversationWithName
  - senderName
  - outgoing
  - text
  - language
  - platform
  - datetime

hangouts:
  DEFAULT_RAW_LOCATION: 'raw/hangouts/Hangouts.json'
messenger:
  DEFAULT_RAW_LOCATION: 'raw/messenger'
telegram:
  USER_DIALOG_MESSAGES_LIMIT: 1000
whatsapp:
  DEFAULT_RAW_LOCATION: 'raw/whatsapp'

